In [10]:
#Q1 - 5부터 14까지의 1차원 ndarray를 생성하여 다음과 같은 화면이 출력되도록 numpy로 데이터를 핸들링하세요"
import numpy as np
print("<출력화면>")
sequence_array = np.arange(start=5, stop=15)

print('sequence array : ', sequence_array)
array_float = sequence_array.astype('float64')
print('array_float : ', array_float)
print('type :',array_float.dtype)

array2 = array_float.reshape(2,5)
print('array2 : \n', array2)
print('shape :', array2.shape)

<출력화면>
sequence array :  [ 5  6  7  8  9 10 11 12 13 14]
array_float :  [ 5.  6.  7.  8.  9. 10. 11. 12. 13. 14.]
type : float64
array2 : 
 [[ 5.  6.  7.  8.  9.]
 [10. 11. 12. 13. 14.]]
shape : (2, 5)


In [11]:
#Q2 - Q1에서 만든 ndarray를 활용하여 다음의 인덱싱 결과를 출력하세요

array_int = array2.astype('int64')
print('Slicing Indexing Result : \n', array_int[0:2, 2:4])
print('Fancy Indexing Result :\n', array_int[[0,1],2:4])
print('Boolean Indexing Result :\n', sequence_array[sequence_array>6])

Slicing Indexing Result : 
 [[ 7  8]
 [12 13]]
Fancy Indexing Result :
 [[ 7  8]
 [12 13]]
Boolean Indexing Result :
 [ 7  8  9 10 11 12 13 14]


In [12]:
#Q3 - 다음의 각 학생들의 성적을 내림차순으로 정렬을 한 후 각 학생의 이름과 원본 행렬의 인덱스 값을 출력하시오

name_array = np.array(['John', 'Mike', 'Sarah', 'Kate', 'Samuel'])
score_array= np.array([78, 95, 84, 98, 88])
print("Student Name : ", name_array)
print("Score :", score_array)


n=len(score_array)
sort_indices_asc = np.argsort(score_array)
decending_indices = sort_indices_asc[::-1][:n]
print('성적 내림차순으로 name_array의 이름 출력:', name_array[decending_indices])
print('성적 내림차순 정렬 시 score_array의 인덱스:', decending_indices)

Student Name :  ['John' 'Mike' 'Sarah' 'Kate' 'Samuel']
Score : [78 95 84 98 88]
성적 내림차순으로 name_array의 이름 출력: ['Kate' 'Mike' 'Samuel' 'Sarah' 'John']
성적 내림차순 정렬 시 score_array의 인덱스: [3 1 4 2 0]


In [13]:
#Q4 - (1) 타이타닉 데이터를 읽어들여 다음의 문제를 완료하시오"
import pandas as pd
titanic_df = pd.read_csv('titanic_train.csv')

#(1) 결손 데이터를 검색하여 Missing 데이터를 처리하고 isna()로 결손 데이터 여부를 출력하시오
titanic_df.isna().sum()
titanic_df['Cabin'] = titanic_df['Cabin'].fillna('C000')
titanic_df['Age'] = titanic_df['Age'].fillna(titanic_df['Age'].mean())
titanic_df['Embarked'] = titanic_df['Embarked'].fillna('S')
titanic_df.isna().sum()

PassengerId    0
Survived       0
Pclass         0
Name           0
Sex            0
Age            0
SibSp          0
Parch          0
Ticket         0
Fare           0
Cabin          0
Embarked       0
dtype: int64

In [14]:
#(2) Age_0(Age=0)변수와 Age_by_10(Age*10)변수와 Family (Siblings + Parch+1)변수를 새로 생성하시오
titanic_df ['Age_0']=0
titanic_df['Age_by_10'] = titanic_df['Age']*10
titanic_df['Family_No'] = titanic_df['SibSp'] + titanic_df['Parch']+1

#(3) Age, SibSp, Parch는 데이터 프레임에서 삭제한 후 상위 3개 데이터를 출력하시오
titanic_df.drop(['SibSp', 'Parch'], axis=1, inplace=True)
print(titanic_df.head(3))

   PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   

                                                Name     Sex   Age  \
0                            Braund, Mr. Owen Harris    male  22.0   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0   
2                             Heikkinen, Miss. Laina  female  26.0   

             Ticket     Fare Cabin Embarked  Age_0  Age_by_10  Family_No  
0         A/5 21171   7.2500  C000        S      0      220.0          2  
1          PC 17599  71.2833   C85        C      0      380.0          2  
2  STON/O2. 3101282   7.9250  C000        S      0      260.0          1  


In [15]:
#(4) 각 연령대(10대 ~ 60대)별 남녀가 몇명인지 구하시오
def get_category(age):
    cat = ''
    if age < 20: cat = '10'
    elif age < 30: cat = '20'
    elif age < 40: cat = '30'
    elif age < 50: cat = '40'
    elif age < 60: cat = '50'
    elif age < 70: cat = '60'
    elif age < 80: cat = '70'
    else : cat = '80'
    
    return cat

titanic_df['Age_cat'] = titanic_df['Age'].apply(lambda x : get_category(x))
titanic_groupby = titanic_df.groupby(['Age_cat','Sex'])['PassengerId'].count()
titanic_groupby

Age_cat  Sex   
10       female     75
         male       89
20       female    125
         male      272
30       female     60
         male      107
40       female     32
         male       57
50       female     18
         male       30
60       female      4
         male       15
70       male        6
80       male        1
Name: PassengerId, dtype: int64